In [1]:
import numpy as np

Creating a matrix using numpy

In [3]:
matrix1 = np.array([[2,3],[7,8]])

print(matrix1)

[[2 3]
 [7 8]]


In [4]:
matrix1.shape

(2, 2)

In [5]:
matrix2 = np.array([[1,2,3],[10,20,30],[100,200,300]])
print(matrix2)

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]]


In [6]:
matrix2.shape

(3, 3)

Creating matrix with random numbers

In [7]:
random_matrix = np.random.randint(100,size=(4,5))

In [8]:
print(random_matrix)

[[63 15  0 63 92]
 [65 85 36 75 83]
 [25 58 30 87 37]
 [22 52 65 96 46]]


Matrix with all the values as 1

In [10]:
matrix3 = np.ones((2,3))
print(matrix3)

[[1. 1. 1.]
 [1. 1. 1.]]


Null matrix or zero matrix

In [12]:
matrix4 = np.zeros((4,4),dtype=int)
print(matrix4)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


Identity matrix

In [15]:
id_matrix = np.eye(6,6,dtype=int)

print(id_matrix)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


Transpose of a matrix

In [16]:
m = np.random.randint(100,size=(6,7))
print(m)

[[82 37 95 26 97 98  1]
 [27 62 70  6  0 94 65]
 [77  1 51 50 80 28 24]
 [ 2 18 79 76 26 50 22]
 [10 53 61 99 57 86 73]
 [74  6 86 70 52  5 69]]


In [17]:
n = np.transpose(m)
print(n)

[[82 27 77  2 10 74]
 [37 62  1 18 53  6]
 [95 70 51 79 61 86]
 [26  6 50 76 99 70]
 [97  0 80 26 57 52]
 [98 94 28 50 86  5]
 [ 1 65 24 22 73 69]]
