In [1]:
# import library
import numpy as np

Matrix addition

In [2]:
# creating two matrices
A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])


In [3]:
print(A)

[[2 3]
 [4 5]]


In [4]:
print(B)

[[6 7]
 [8 9]]


In [5]:
print(A+B)

[[ 8 10]
 [12 14]]


In [6]:
print(A-B)

[[-4 -4]
 [-4 -4]]


Multiplication of matrix (scalar)

In [7]:
x=5
y = np.random.randint(20,size=(4,5))

z = np.multiply(x,y)
print(z)

[[30 95 55 65  0]
 [25  5 75 95 75]
 [45 70 10 70 60]
 [45 85 85 60  0]]


In [8]:
print(y)

[[ 6 19 11 13  0]
 [ 5  1 15 19 15]
 [ 9 14  2 14 12]
 [ 9 17 17 12  0]]


Multiplication of 2 matrices

In [10]:
a = np.random.randint(5,size=(3,3))
b = np.random.randint(5,size=(3,4))


In [11]:
print(a)

[[1 4 2]
 [4 3 1]
 [1 2 1]]


In [12]:
print(b)

[[3 3 0 1]
 [0 0 2 0]
 [1 2 3 2]]


In [13]:
res = np.dot(a,b)
print(res)

[[ 5  7 14  5]
 [13 14  9  6]
 [ 4  5  7  3]]
